### ISSUE TITLE
Reorganize repo?

### ISSUE THREAD

**Issue by wdlkmpx** [DebianDog/MakeLive#3]
This repo is huge. Maybe it should be split into several repos..?

One for scripts, one for packages, one for data, etc

I just brifely tested debiandog jessie and it works fine. But i wonder where the important stuff is, i don't plan to install debian (i had installed wheezy some days ago, but i wiped it shortly after), but would like to edit scripts and configs for better defaults, e.g: xorg mouse keys enabled by default

**Comment by fredx181** [comment]
Sorry for the delay, didn't notice your message earlier.

> This repo is huge. Maybe it should be split into several repos..?  
  
I think it's better to keep all in one place, and besides that. it will be a lot of work to change things, this is mostly a one man's project.

> I just brifely tested debiandog jessie and it works fine. But i wonder where the important stuff is, i don't plan to install debian (i had installed wheezy some days ago, but i wiped it shortly after), but would like to edit scripts and configs for better defaults, e.g: xorg mouse keys enabled by default

If you can be more specific about what you mean with "important stuff" (and which debiandog jessie version), I can answer maybe.

Fred

**Comment by wdlkmpx** [comment]
Debian dog jessie xfce. I see debiandog has some scripts, like probepart and probedisk.

I wrote this cli/gui wizard so i can easily install debian from puppy [dpup stretch 2018-07] (complete installation), it worked for me, i just installed debian jessie + lxde, and it works ok so far
[install-debian-to-hd.zip](https://github.com/DebianDog/MakeLive/files/2215836/install-debian-to-hd.zip)
it automatically creates a grub4dos menu, it's not finished/polished... i also added a couple lines from make live (to create the 'user' user). for the first time i used an unprivileged user to log in to a debian system ...

But that script uses woofce's probepart and probedisk which are way more advanced than the old scripts, i can port many scripts and stuff from woofce, i could do stuff here... it will confuse you though, also i don't know if i'll be active i've been receiving bad news lately, and on top of that there's the reorganization 'issue' i'm raising...

I understand that learning git takes too much time, i see you're using it more like a file hosting, i think it's fine...

Anyway, i just wanted to say something, i'd also welcome an lxde dog iso for me hehe.., and the user should be 'user' instead of 'puppy'.. it's not a secret i'm not a fan of the '*puppy*' or '*dog*' names ...
