### ISSUE TITLE
Where can the AppImage be downloaded?

### ISSUE THREAD

**Issue by probonopd** [DebianDog/MakeLive#5]
https://github.com/DebianDog/MakeLive/blob/7fdd0f5abb144d5d81a046afbadf8d9132b5c37a/Readme-build-devuandog-beowulf.html#L319

Where can the AppImage be downloaded?

**Comment by fredx181** [comment]
Here (under "Download:")
https://debiandog.github.io/MakeLive/Readme-build-devuandog-beowulf.html 
(link is now on top of the README)  
BTW... Thanks very much for all your work during the years ! I learned a lot and appimages can be very handy. 
I remember you had the portablelinuxapps forum, maybe you remember me, I was the one who experimented with portable wine and youtube-downloader.

Fred

**Comment by probonopd** [comment]
Something is going wrong...

```
me@host:~$ chmod +x Downloads/mklive-beowulf64 

me@host:~$ Downloads/mklive-beowulf64 
Segmentation fault

me@host:~$ Downloads/mklive-beowulf64 --appimage-extract
Segmentation fault

me@host:~$ Downloads/mklive-beowulf64 --appimage-version
Segmentation fault

me@host:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
```

**Comment by fredx181** [comment]
Sorry, most of the time I login as root, so didn't notice earlier that it doesn't run as regular user.
Running with sudo should work.
Will update the page later with info about that.
Maybe it's because I created the appimage as being root ?

**Comment by probonopd** [comment]
With `sudo` it works indeed. It should print out an error message at least. Thanks!

**Comment by fredx181** [comment]
Should be fixed now (gives message (about required to run with sudo) when running as normal user)
  
@probonopd   
I used your appimagetool now to create the appimage, earlier I used the commands from the AppimageKit README:  
```
mksquashfs Your.AppDir Your.squashfs -root-owned -noappend
cat runtime >> Your.AppImage
cat Your.squashfs >> Your.AppImage
chmod a+x Your.AppImage
```
What is missing above that it gives a segmentation fault when running as normal user ?  

Fred

**Comment by probonopd** [comment]
Great question, I don't know. Using `appimagetool` should be safer because it is much better tested than the manual method.

**Comment by probonopd** [comment]
![](https://raw.githubusercontent.com/AppImage/appimage.github.io/b9250226a3b716171816a5a64a162b0cb5f084de/database/mklive-beowulf64/screenshot.png)

probably means that `Terminal=true` should be set in the desktop file.

**Comment by fredx181** [comment]
> probably means that Terminal=true should be set in the desktop file. 
  
Even then, just clicking on the appimage will exit the program because it requires arguments, e.g. `-gui `or `-cli`

> Great question, I don't know. Using appimagetool should be safer because it is much better tested than the manual method. 
    
Ah, pity, please let me know if you find out at sometime what's missing for the manual method.

**Comment by probonopd** [comment]
> Even then, just clicking on the appimage will exit the program because it requires arguments, e.g. -gui or -cli

Could/does it print some standard message (help text) when invoked without arguments or wrong arguments?
